theme: jekyll-theme-slate
title: Práctica Economía Laboral 2S23
description: Curso Práctico de Economía Laboral 2S 2023 - Prof. Junghanss Juan Cruz
url: "https://junghanss.github.io/"
layout: default
