theme: jekyll-theme-slate
title: Práctica Economía Laboral 2S24
description: Curso Práctico de Economía Laboral 2S 2024 - Prof. Junghanss Juan Cruz
url: "https://junghanss.github.io/"
layout: default
